# Usa una imagen oficial de Python como base
FROM python:3.11-slim

# Variables de entorno
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Directorio de trabajo
WORKDIR /app

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia los archivos
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copia el resto del código
COPY . .

# Expón el puerto (usualmente 8000 para Django)
EXPOSE 7000

# Comando por defecto
CMD ["gunicorn", "django_ca_core.wsgi:application", "--bind", "0.0.0.0:7000", "--timeout", "300"]
