# Generated by Django 5.2 on 2025-04-30 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifying_authority', models.SmallIntegerField(choices=[(0, 'cerfificado de produccion'), (1, 'cerfificado de desarrollo')])),
                ('domain', models.CharField(max_length=250, verbose_name='Dominio para el certificado ej. servicio.ucr.ac.cr')),
                ('institution_unit', models.CharField(default='ND', max_length=250, verbose_name='Unidad en el certificado')),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('public_certificate', models.TextField()),
                ('server_sign_key', models.TextField()),
                ('server_public_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
