# Generated by Django 5.2 on 2025-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Nombre de la aplicación'),
            preserve_default=False,
        ),
    ]
