# Generated by Django 5.2 on 2025-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates_generator', '0002_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Activo'), (1, 'Revocado')], default=0),
        ),
    ]
